In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('data/insurance_data.csv')

In [15]:
df.head(1)

,TXN_DATE_TIME,TRANSACTION_ID,CUSTOMER_ID,POLICY_NUMBER,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,...,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID
0,2020-06-01 00:00:00,TXN00000001,A00003822,PLC00008468,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,...,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TXN_DATE_TIME             10000 non-null  object
 1   TRANSACTION_ID            10000 non-null  object
 2   CUSTOMER_ID               10000 non-null  object
 3   POLICY_NUMBER             10000 non-null  object
 4   POLICY_EFF_DT             10000 non-null  object
 5   LOSS_DT                   10000 non-null  object
 6   REPORT_DT                 10000 non-null  object
 7   INSURANCE_TYPE            10000 non-null  object
 8   PREMIUM_AMOUNT            10000 non-null  float64
 9   CLAIM_AMOUNT              10000 non-null  int64
 10  CUSTOMER_NAME             10000 non-null  object
 11  ADDRESS_LINE1             10000 non-null  object
 12  ADDRESS_LINE2             1495 non-null   object
 13  CITY                      9946 non-null   object
 14  STATE                     10000 non-null  object
 15  POSTAL_CODE               10000 non-null  int64
 16  SSN                       10000 non-null  object
 17  MARITAL_STATUS            10000 non-null  object
 18  AGE                       10000 non-null  int64
 19  TENURE                    10000 non-null  int64
 20  EMPLOYMENT_STATUS         10000 non-null  object
 21  NO_OF_FAMILY_MEMBERS      10000 non-null  int64
 22  RISK_SEGMENTATION         10000 non-null  object
 23  HOUSE_TYPE                10000 non-null  object
 24  SOCIAL_CLASS              10000 non-null  object
 25  ROUTING_NUMBER            10000 non-null  int64
 26  ACCT_NUMBER               10000 non-null  object
 27  CUSTOMER_EDUCATION_LEVEL  9471 non-null   object
 28  CLAIM_STATUS              10000 non-null  object
 29  INCIDENT_SEVERITY         10000 non-null  object
 30  AUTHORITY_CONTACTED       8055 non-null   object
 31  ANY_INJURY                10000 non-null  int64
 32  POLICE_REPORT_AVAILABLE   10000 non-null  int64
 33  INCIDENT_STATE            10000 non-null  object
 34  INCIDENT_CITY             9954 non-null   object
 35  INCIDENT_HOUR_OF_THE_DAY  10000 non-null  int64
 36  AGENT_ID                  10000 non-null  object
 37  VENDOR_ID                 6755 non-null   object
dtypes: float64(1), int64(9), object(28)
memory usage: 2.9+ MB

In [30]:
df.isnull().sum()

TXN_DATE_TIME               0
TRANSACTION_ID              0
CUSTOMER_ID                 0
POLICY_NUMBER               0
POLICY_EFF_DT               0
LOSS_DT                     0
REPORT_DT                   0
INSURANCE_TYPE              0
PREMIUM_AMOUNT              0
CLAIM_AMOUNT                0
CUSTOMER_NAME               0
ADDRESS_LINE1               0
CITY                        0
STATE                       0
POSTAL_CODE                 0
SSN                         0
MARITAL_STATUS              0
AGE                         0
TENURE                      0
EMPLOYMENT_STATUS           0
NO_OF_FAMILY_MEMBERS        0
RISK_SEGMENTATION           0
HOUSE_TYPE                  0
SOCIAL_CLASS                0
ROUTING_NUMBER              0
ACCT_NUMBER                 0
CUSTOMER_EDUCATION_LEVEL    0
CLAIM_STATUS                0
INCIDENT_SEVERITY           0
AUTHORITY_CONTACTED         0
ANY_INJURY                  0
POLICE_REPORT_AVAILABLE     0
INCIDENT_STATE              0
INCIDENT_CITY               0
INCIDENT_HOUR_OF_THE_DAY    0
AGENT_ID                    0
VENDOR_ID                   0
dtype: int64

In [18]:
df.describe()

,PREMIUM_AMOUNT,CLAIM_AMOUNT,POSTAL_CODE,AGE,TENURE,NO_OF_FAMILY_MEMBERS,ROUTING_NUMBER,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_HOUR_OF_THE_DAY
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000
mean,88.508595,16563.830000,48288.830500,44.466100,62.949800,4.488400,7.052882e+07,0.699100,0.692800,11.604000
std,48.315874,22037.489735,32467.389801,11.516827,32.890604,1.712588,3.451879e+07,0.458672,0.461356,6.877101
min,6.000000,100.000000,1001.000000,25.000000,6.000000,2.000000,1.000074e+07,0.000000,0.000000,0.000000
25%,62.015000,2000.000000,21061.000000,34.000000,34.000000,3.000000,4.071761e+07,0.000000,0.000000,6.000000
50%,88.835000,7000.000000,37206.000000,45.000000,64.000000,4.000000,7.036614e+07,1.000000,1.000000,12.000000
75%,121.902500,21000.000000,80004.000000,54.000000,92.000000,6.000000,1.000638e+08,1.000000,1.000000,18.000000
max,200.000000,100000.000000,99669.000000,64.000000,119.000000,7.000000,1.299981e+08,1.000000,1.000000,23.000000

In [ ]:
null_rows = df[df['INCIDENT_CITY'].isnull()]
null_rows

In [22]:
df1 = pd.read_csv('data/vendor_data.csv')

In [ ]:
df1

In [24]:
df.shape

(10000, 38)

In [26]:
result = df[
    (df['AUTHORITY_CONTACTED'].isnull()) &
    (df['POLICE_REPORT_AVAILABLE'] == 1)
]

result

,TXN_DATE_TIME,TRANSACTION_ID,CUSTOMER_ID,POLICY_NUMBER,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,...,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID
12,2020-06-01 00:00:00,TXN00000013,A00003693,PLC00007839,2019-06-12,2020-05-24,2020-05-27,Health,157.95,11000,...,A,Major Loss,NaN,0,1,KY,Louisville,22,AGENT00015,VNDR00191
19,2020-06-01 00:00:00,TXN00000020,A00005314,PLC00001411,2013-11-08,2020-05-17,2020-05-22,Life,77.17,68000,...,A,Total Loss,NaN,1,1,CO,Arvada,1,AGENT00490,NaN
28,2020-06-01 00:00:00,TXN00000029,A00004865,PLC00007448,2016-08-29,2020-05-20,2020-05-25,Property,159.20,37000,...,A,Minor Loss,NaN,0,1,MD,Pasadena,7,AGENT00431,VNDR00339
34,2020-06-02 00:00:00,TXN00000035,A00007890,PLC00005354,2014-08-13,2020-05-17,2020-05-22,Life,95.16,74000,...,A,Major Loss,NaN,1,1,KY,Louisville,13,AGENT00313,VNDR00226
45,2020-06-02 00:00:00,TXN00000046,A00000956,PLC00009442,2012-10-01,2020-05-28,2020-05-29,Travel,90.04,5000,...,A,Minor Loss,NaN,1,1,AR,Farmington,5,AGENT00969,VNDR00071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9968,2021-06-29 00:00:00,TXN00009969,A00000660,PLC00005482,2018-09-11,2021-06-15,2021-06-20,Motor,72.96,7000,...,D,Total Loss,NaN,1,1,AR,Fayetteville,14,AGENT00204,NaN
9971,2021-06-29 00:00:00,TXN00009972,A00002887,PLC00003785,2020-01-16,2021-06-17,2021-06-22,Life,67.11,81000,...,A,Total Loss,NaN,1,1,GA,Garden City,2,AGENT00673,VNDR00187
9984,2021-06-30 00:00:00,TXN00009985,A00002790,PLC00002064,2013-09-04,2021-06-15,2021-06-20,Life,75.47,23000,...,A,Minor Loss,NaN,1,1,AL,Montgomery,10,AGENT00589,VNDR00429
9991,2021-06-30 00:00:00,TXN00009992,A00008542,PLC00000807,2018-03-29,2021-06-26,2021-06-27,Travel,88.20,3000,...,A,Minor Loss,NaN,1,1,AZ,Glendale,16,AGENT01054,NaN
9997,2021-06-30 00:00:00,TXN00009998,A00004230,PLC00006613,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,...,A,Major Loss,NaN,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104

In [27]:
pd.crosstab(
    df['AUTHORITY_CONTACTED'],
    df['POLICE_REPORT_AVAILABLE'],
    dropna=False
)

POLICE_REPORT_AVAILABLE     0     1
AUTHORITY_CONTACTED
Ambulance                1261  2821
Other                     309   682
Police                    924  2058
NaN                       578  1367

In [28]:
df =df.drop(columns=['ADDRESS_LINE2'])

In [29]:
# Thay tất cả giá trị null trong dataframe thành 'Unknown'

df = df.fillna('Unknown')

In [32]:
df1.isnull().sum()

VENDOR_ID          0
VENDOR_NAME        0
ADDRESS_LINE1      0
ADDRESS_LINE2    503
CITY               6
STATE              0
POSTAL_CODE        0
dtype: int64

In [35]:
df = df.merge(
    df1[['VENDOR_ID', 'VENDOR_NAME']],
    on='VENDOR_ID',
    how='left'
)

In [36]:
df2 =  pd.read_csv('data/employee_data.csv')

In [38]:
df =df.merge(
    df2[['AGENT_ID', 'AGENT_NAME', 'DATE_OF_JOINING' , 'EMP_ROUTING_NUMBER', 'EMP_ACCT_NUMBER']],
    on = 'AGENT_ID',
    how = 'left'    
)

In [41]:
df = df.fillna('Unknown')

In [42]:
df.to_csv('data/insurance_data_cleaned.csv', index=False)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TXN_DATE_TIME             10000 non-null  object
 1   TRANSACTION_ID            10000 non-null  object
 2   CUSTOMER_ID               10000 non-null  object
 3   POLICY_NUMBER             10000 non-null  object
 4   POLICY_EFF_DT             10000 non-null  object
 5   LOSS_DT                   10000 non-null  object
 6   REPORT_DT                 10000 non-null  object
 7   INSURANCE_TYPE            10000 non-null  object
 8   PREMIUM_AMOUNT            10000 non-null  float64
 9   CLAIM_AMOUNT              10000 non-null  int64
 10  CUSTOMER_NAME             10000 non-null  object
 11  ADDRESS_LINE1             10000 non-null  object
 12  CITY                      10000 non-null  object
 13  STATE                     10000 non-null  object
 14  POSTAL_CODE               10000 non-null  int64
 15  SSN                       10000 non-null  object
 16  MARITAL_STATUS            10000 non-null  object
 17  AGE                       10000 non-null  int64
 18  TENURE                    10000 non-null  int64
 19  EMPLOYMENT_STATUS         10000 non-null  object
 20  NO_OF_FAMILY_MEMBERS      10000 non-null  int64
 21  RISK_SEGMENTATION         10000 non-null  object
 22  HOUSE_TYPE                10000 non-null  object
 23  SOCIAL_CLASS              10000 non-null  object
 24  ROUTING_NUMBER            10000 non-null  int64
 25  ACCT_NUMBER               10000 non-null  object
 26  CUSTOMER_EDUCATION_LEVEL  10000 non-null  object
 27  CLAIM_STATUS              10000 non-null  object
 28  INCIDENT_SEVERITY         10000 non-null  object
 29  AUTHORITY_CONTACTED       10000 non-null  object
 30  ANY_INJURY                10000 non-null  int64
 31  POLICE_REPORT_AVAILABLE   10000 non-null  int64
 32  INCIDENT_STATE            10000 non-null  object
 33  INCIDENT_CITY             10000 non-null  object
 34  INCIDENT_HOUR_OF_THE_DAY  10000 non-null  int64
 35  AGENT_ID                  10000 non-null  object
 36  VENDOR_ID                 10000 non-null  object
 37  VENDOR_NAME               10000 non-null  object
 38  AGENT_NAME                10000 non-null  object
 39  DATE_OF_JOINING           10000 non-null  object
 40  EMP_ROUTING_NUMBER        10000 non-null  int64
 41  EMP_ACCT_NUMBER           10000 non-null  object
dtypes: float64(1), int64(10), object(31)
memory usage: 3.2+ MB

In [44]:
# Danh sách các cột thời gian
date_cols = [
    'TXN_DATE_TIME',
    'POLICY_EFF_DT',
    'LOSS_DT',
    'REPORT_DT',
    'DATE_OF_JOINING'
]

# Convert sang datetime
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# Xem min max
for col in date_cols:
    print(f"\n===== {col} =====")
    print("Min:", df[col].min())
    print("Max:", df[col].max())

===== TXN_DATE_TIME =====
Min: 2020-06-01 00:00:00
Max: 2021-06-30 00:00:00

===== POLICY_EFF_DT =====
Min: 2010-06-01 00:00:00
Max: 2020-01-31 00:00:00

===== LOSS_DT =====
Min: 2020-05-12 00:00:00
Max: 2021-06-29 00:00:00

===== REPORT_DT =====
Min: 2020-05-17 00:00:00
Max: 2021-06-29 00:00:00

===== DATE_OF_JOINING =====
Min: 1990-06-25 00:00:00
Max: 2018-06-24 00:00:00